### ISSUE TITLE
Internal SSD is not detected (while show all devices is selected)

### ISSUE THREAD

**Issue by abhisheksih** [AbhaySingh15/Acer-aspire-7-A715-75G-Opencore-EFI#2]
While installing Big Sur on same machine, disk utility is unable to detect internal SSD. I tried a lot of stuff like kexts, AHCI etc. but none worked.
 And one more problem, in  this repository EFI folder only contains OC folder, not BOOT folder, so how can anyone boot from this EFI. Thanks.

**Comment by AbhaySingh15** [comment]
your ssd is not detected because you probably have'nt switched from RST to AHCI mode. 
Refer to this [https://community.acer.com/en/discussion/592158/switch-from-raid-to-ahci-on-acer-nitro-5-an515-54](url) for more info.
For the boot folder as i dual boot mac os and windows so i didn't upload it in the repo.

**Comment by abhisheksih** [comment]
Thanks a lot ! You saved me.
